name: driver_carpool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  firebase_storage: ^11.5.5
  google_sign_in: ^6.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  sqflite: ^2.3.0
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/CarPool.png